version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    restart: always
    networks:
      - server-network
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    expose:
      - "27017"
  discovery:
    build: ./Eureka_server
    ports:
      - 8761:8761
    image: eureka_image
    networks:
      - server-network
  gateway:
    build: ./Api_Gateway_server
    ports:
      - 8081:8081
    image: gateway
    networks:
      - server-network
    depends_on:
      - discovery
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/

  blog-ms:
    build: ./Blog-management-microservice
    ports:
      - 8001:8001
    image: blog-ms
    networks:
      - server-network
    depends_on:
      - discovery
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
  auction-ms:
    build: ./auction-management-microservice
    ports:
      - 8002:8002
    image: auction-ms
    depends_on:
      - discovery
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    networks:
      - server-network
  event-ms:
    build: ./event-management-microservice
    ports:
      - 8004:8004
    image: event-ms
    depends_on:
      - discovery
    networks:
      - server-network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
  order-ms:
    build: ./order-management-microservice
    ports:
      - 8005:8005
    image: order-ms
    depends_on:
      - discovery
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    networks:
      - server-network
  gallery-ms:
    build: ./Gallery-management-microservice
    ports:
      - 8006:8006
    image: gallery-ms
    depends_on:
      - discovery
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    networks:
      - server-network
  user-ms:
    build: ./user-management-microservice
    ports:
      - 3001:3001
    image: user-ms
    command: npm run start:prod
    restart: unless-stopped
    networks:
      - server-network
    depends_on:
      - discovery
      - mongodb
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
  client-ms:
    build: ./artlab-client
    ports:
      - 3000:3000
    image: client-ms
    networks:
      - server-network

networks:
  server-network:
volumes:
  mongodb_data_container: